### ISSUE TITLE
ST3 unresponsive

### ISSUE THREAD

**Issue by karldanninger** [Slava/tern-meteor-sublime#15]
When I try to do 'jump to definition' on anything, Sublime just beach balls. I've tried small & large apps.
Is there a way I can debug Sublime to give you a better idea of what is happening?

I'm using build 3083.

**Comment by Slava** [comment]
This is .. very sad. To get an initial diagnose, see what is blocking: open an activity monitor and see if there is a node process running on 100% cpu or is it sublime. Also, you can open a console in sublime and try to observe logs. You can put logs into the python code if you open your local copy of the plugin.

**Comment by krstffr** [comment]
This is the case for me as well, it will hang Sublime Text 3 instantly on keydown.

A couple of node processes (I think four?) gets spawned and run @ 100%. And they won't die even if I force quit Sublime, so I need to force quit those as well.

**Comment by krstffr** [comment]
OK there are only two node processes being spawned, not four! Unless you do this twice. :)

**Comment by steve-ross** [comment]
The first couple of times I try an autocompletion it times out on me as well but after a couple of those it seems to cache everything and the editor works fine.

**Comment by elvismercado** [comment]
Since iv'e been using the Meteor Autocomplete package e get a timeout alert multiple times while writing code. It gets really annoying.
This is what comes up in the SublimeText console when it happens:

![screen shot 2015-07-01 at 10 22 05](https://cloud.githubusercontent.com/assets/3658208/8450469/7ce55d40-1fdb-11e5-98c1-dd8c0beb2c05.png)

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 296, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/elvismercado/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/tern.py", line 48, in on_selection_modified_async
    on_selection_modified(view)
  File "/Users/elvismercado/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/tern.py", line 28, in on_selection_modified
    if pfile is not None: show_argument_hints(pfile, view)
  File "/Users/elvismercado/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/tern.py", line 454, in show_argument_hints
    render_argument_hints(pfile, view, parsed, argpos)
  File "/Users/elvismercado/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/tern.py", line 469, in render_argument_hints
    msg = ftype["name"] + "("
KeyError: 'name'`

**Comment by Slava** [comment]
I mean, TernJS is a single-threaded server that does CPU-heavy work. I can't fix this. If this doesn't work for your project, don't use this plugin. This is as simple as this. I worked hard to get the features out, but fixing the performance problems in ternjs, is not something I will work on.

**Comment by elvismercado** [comment]
Ok, now i understand.
Thnx

**Comment by newswim** [comment]
Did that temporary fix help? It works great for looking up function definitions (brilliantly, actually) -- but as soon as I start to type, beach ball.

**Comment by Kostanos** [comment]
Same here, Time Out error

**Comment by rikkuporta** [comment]
I have a similiar problem, but mine would be solved if Tern would ignore one specific folder (which I believe is loaded into memory and stuff). How can I do this?

**Comment by Kostanos** [comment]
Which folders you should exclude?
I'm excluding (in project settings), it helps, but some time it still keep getting errors:

```
    "ternjs":
    {
        "exclude":
        [
            ".meteor/**",
            "node_modules/**",
            ".gagarin"
        ]
    }
```
