### ISSUE TITLE
New error after updating to Sublime 3092

### ISSUE THREAD

**Issue by ssteinerx** [Slava/tern-meteor-sublime#19]
Failed to start server:

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/Users/ssteiner/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/defs/ecma5.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at readJSON (/Users/ssteiner/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:72:17)
    at findDefs (/Users/ssteiner/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:126:26)
    at startServer (/Users/ssteiner/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:241:14)
    at Object.<anonymous> (/Users/ssteiner/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:232:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by Slava** [comment]
https://github.com/Slava/tern-meteor-sublime/issues/12

**Comment by TrungNghia1908** [comment]
https://jaredbarriere.wordpress.com/2016/08/02/sublime-text-3-meteor-auto-complete-ternjs/
This solution work for me.
