### ISSUE TITLE
Error loading Sublime Text after installing.

### ISSUE THREAD

**Issue by josephdburdick** [Slava/tern-meteor-sublime#6]
Look at this: it appears to have your the Slava username as part of the filepath. Fails hard.

```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/slava/log.txt'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at Object.fs.appendFileSync (fs.js:1017:6)
    at Object.<anonymous> (/Users/jb/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:149:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by josephdburdick** [comment]
@Slava Looks like these aren't issues in the repo for this project but they exist in the package I got from Package Manager. Are you sure you have the most up-to-date code on Package Manager?

**Comment by Slava** [comment]
@josephdburdick that was a mistake on my part. I already pushed a fix to Package Control, but it takes several hours to sync in (not in my control). Should be good once it is updated to 1.0.4 or 1.0.5 on this page https://packagecontrol.io/packages/Meteor%20Autocomplete%20(TernJS)

**Comment by josephdburdick** [comment]
@Slava I see you made the change in dca496 right before I forked it and tried to fix the error myself. Package Manager is already updated and running without errors. :+1: Thanks!

**Comment by Slava** [comment]
Yeah! It was a silly mistake that I made: left some hardcoded logging around.
